### ISSUE TITLE
Both CHANGEKIND_HIGH_TO_LOW & CHANGEKIND_LOW_TO_HIGH marco are LOW

### ISSUE THREAD

**Issue by tedani** [prampec/arduino-pcimanager#2]
In PciListenerImp.h:
# define CHANGEKIND_HIGH_TO_LOW LOW
# define CHANGEKIND_LOW_TO_HIGH LOW

Is it wrong?

**Comment by prampec** [comment]
Sorry, I've missed these comments.
Thank you to pointing that out.
Fixed.
